#define UTS_RELEASE "1.0"
#define UTS_VERSION "#21 Tue Mar 23 07:37:21 CST 2021"
#define LINUX_COMPILE_TIME "07:37:21"
#define LINUX_COMPILE_BY "ubuntu"
#define LINUX_COMPILE_HOST "ubuntu"
#define LINUX_COMPILE_DOMAIN "(none)"
