#define UTS_RELEASE "1.0"
#define UTS_VERSION "#64 2021年 03月 24日 星期三 14:02:38 CST"
#define LINUX_COMPILE_TIME "14:02:38"
#define LINUX_COMPILE_BY "ubuntu"
#define LINUX_COMPILE_HOST "ubuntu-virtual-machine"
#define LINUX_COMPILE_DOMAIN "(none)"
